/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadResumeRouteImport } from './routes/download-resume'
import { Route as IndexRouteImport } from './routes/index'

const DownloadResumeRoute = DownloadResumeRouteImport.update({
  id: '/download-resume',
  path: '/download-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-resume': typeof DownloadResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-resume': typeof DownloadResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download-resume': typeof DownloadResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download-resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download-resume'
  id: '__root__' | '/' | '/download-resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadResumeRoute: typeof DownloadResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download-resume': {
      id: '/download-resume'
      path: '/download-resume'
      fullPath: '/download-resume'
      preLoaderRoute: typeof DownloadResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadResumeRoute: DownloadResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
